#ifndef DEEPLEARN_GLOBALS_H
#define DEEPLEARN_GLOBALS_H

#define DEEPLEARN_TEMP_DIRECTORY "/tmp/"
#define DEEPLEARN_HISTORY_SIZE   1024
#define DEEPLEARN_UNKNOWN_ERROR  9999
#define DEEPLEARN_UNKNOWN_VALUE  -9999

#endif
