#ifndef DEEPLEARN_GLOBALS_H
#define DEEPLEARN_GLOBALS_H

#define DEEPLEARN_TEMP_DIRECTORY "/tmp/"
#define DEEPLEARN_HISTORY_SIZE   1024
#define DEEPLEARN_UNKNOWN_ERROR  9999
#define DEEPLEARN_UNKNOWN_VALUE  -9999
#define DEEPLEARN_MAX_FIELD_LENGTH_CHARS 1024
#define DEEPLEARN_MAX_CSV_INPUTS 2048
#define DEEPLEARN_MAX_CSV_OUTPUTS 1024

/* The number of bits per character in a text string */
#define CHAR_BITS (sizeof(char)*8)

#endif
